- name: Update GRUB
  command: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: Redémarrer pour appliquer les changements
  reboot:
    msg: "Rebooting after updating GRUB configuration and unified kernel image."
    pre_reboot_delay: 10
    post_reboot_delay: 30