---
# Grub password
- name: Ajouter le mot de passe GRUB haché au fichier de configuration
  lineinfile:
    path: /etc/grub.d/40_custom
    line: |
      set superusers="root"
      password_pbkdf2 root {{ grub_password }}
    create: yes

- name: Mettre à jour la configuration de GRUB
  command: grub2-mkconfig -o /boot/grub2/grub.cfg

- name: Redémarrer la machine pour appliquer les changements
  reboot:
    msg: "Rebooting after GRUB password change"
    pre_reboot_delay: 10
    post_reboot_delay: 30