---
# Grub password
- name: Ajouter le mot de passe GRUB haché au fichier de configuration
  lineinfile:
    path: /etc/grub.d/40_custom
    line: |
      set superusers="root"
      password_pbkdf2 root {{ grub_password }}
    create: yes

- name: Mettre à jour la configuration de GRUB
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  notify:
    - Redémarrer pour appliquer les changements

# Secure boot

# IOMMU
- name: Ensure 'iommu=force' is in GRUB_CMDLINE_LINUX
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: "GRUB_CMDLINE_LINUX=\"iommu=force {{ grub_cmdline_linux }}\""
  vars:
    grub_cmdline_linux: "{{ lookup('pipe', 'grep ^GRUB_CMDLINE_LINUX= /etc/default/grub | cut -d\\\" -f2') }}"
  notify:
    - Update GRUB


- name: Ensure 'iommu=force' is added to /boot/grub/menu.lst (if exists)
  lineinfile:
    path: /boot/grub/menu.lst
    regexp: '^kernel'
    line: "kernel /vmlinuz-$(uname -r) iommu=force"
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_version'] < '8.0'
  ignore_errors: yes
  notify:
    - Update GRUB

# Memory options
- name: Extract current GRUB_CMDLINE_LINUX value
  shell: grep ^GRUB_CMDLINE_LINUX= /etc/default/grub | cut -d'"' -f2
  register: grub_cmdline_linux_value

- name: Ensure required kernel parameters are in GRUB_CMDLINE_LINUX
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: "GRUB_CMDLINE_LINUX=\"{{ grub_cmdline_linux_value.stdout }} {{ additional_kernel_params | join(' ') }}\""
  vars:
    additional_kernel_params:
      - l1tf=full,force
      - page_poison=on
      - pti=on
      - slab_nomerge=yes
      - slub_debug=FZP
      - spec_store_bypass_disable=seccomp
      - spectre_v2=on
      - mds=full,nosmt
      - mce=0
      - page_alloc.shuffle=1
      - rng_core.default_quality=500
  notify:
    - Update GRUB
    - Redémarrer pour appliquer les changements
