---
# Grub password
- name: Ajouter le mot de passe GRUB haché au fichier de configuration
  lineinfile:
    path: /etc/grub.d/40_custom
    line: |
      set superusers="root"
      password_pbkdf2 root {{ grub_password }}
    create: yes

- name: Mettre à jour la configuration de GRUB
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  notify:
    - Redémarrer pour appliquer les changements

# Secure boot

# IOMMU
- name: Ensure 'iommu=force' is in GRUB_CMDLINE_LINUX
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: "GRUB_CMDLINE_LINUX=\"iommu=force {{ grub_cmdline_linux }}\""
  vars:
    grub_cmdline_linux: "{{ lookup('pipe', 'grep ^GRUB_CMDLINE_LINUX= /etc/default/grub | cut -d\\\" -f2') }}"
  notify:
    - Update GRUB


- name: Ensure 'iommu=force' is added to /boot/grub/menu.lst (if exists)
  lineinfile:
    path: /boot/grub/menu.lst
    regexp: '^kernel'
    line: "kernel /vmlinuz-$(uname -r) iommu=force"
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_version'] < '8.0'
  ignore_errors: yes
  notify:
    - Update GRUB

