---
- name: Disabling and stopping the non-necessary services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop: "{{ services_list }}"


- name: "Disabling non-essential features of services"
  community.general.capabilities:
    path: "{{ item.key }}"
    state: absent
    capability: "{{ item.value }}"
  loop: "{{ capabilities_map | dict2items }}"

# - name: "Configuring the privileges of the services"

# - name: "Partitioning the services"

# - name: "Hardening the partitioning components"

# Limit the elevation to root via su to the members of the group 'wheel ' only part 1
- name: "Secure remote authentication with PAM 1"
  ansible.builtin.template:
    src: su.j2
    dest: /etc/pam.d/su
    owner: root
    group: wheel
    mode: '0644'


# Limit the elevation to root via su to the members of the group 'wheel ' only part 2
- name: "Secure remote authentication with PAM 2"
  ansible.builtin.template:
    src: su-l.j2
    dest: /etc/pam.d/su-l
    owner: root
    group: wheel
    mode: '0644'


# At least 12 characters of 3 different classes among the uppercase letters ,
# lowercase letters , numbers and others by prohibiting repetition
# of a character
- name: "Secure remote authentication with PAM 3"
  ansible.builtin.template:
    src: passwd.j2
    dest: /etc/pam.d/passwd
    owner: root
    group: wheel
    mode: '0644'

#Account blocking for 5 min after 3 failures part 1
- name: "Secure remote authentication with PAM 4"
  ansible.builtin.template:
    src: passwd.j2
    dest: /etc/pam.d/login
    owner: root
    group: wheel
    mode: '0644'

#Account blocking for 5 min after 3 failures part 2
- name: "Secure remote authentication with PAM 5"
  ansible.builtin.template:
    src: sshd.j2
    dest: /etc/pam.d/sshd
    owner: root
    group: wheel
    mode: '0644'


# - name: "Protecting the stored passwords"

# - name: "Securingaccess to remote user databases"

# - name: "Separating the system accounts and directory administrator"

# - name: "Implementing a logging system"

# - name: "Implementing dedicated service activity journals"

# - name: "Logging the system activity with auditd"

# - name: "Hardening the local messaging service"

# - name: "Configuring aliases for service accounts"

# - name: "Sealing and checking files integrity"

# - name: "Protecting the sealing database"

# - name: "Partitioning the network services"

# - name: "Hardening and monitoring the exposed services"

# - name: "Minimizing the attack surface of network services"
